// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckboxController from "./checkbox_controller"
application.register("checkbox", CheckboxController)

import ColumnsFilterController from "./columns_filter_controller"
application.register("columns-filter", ColumnsFilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PaginationController from "./pagination_controller"
application.register("pagination", PaginationController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
