version: '2.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependencies  # Specify the build target for dependencies
    platform: linux/amd64  # Adjust the platform accordingly
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: h0mew0rk
      POSTGRES_DB: EasyArtDB_production

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: h0mew0rk
      POSTGRES_DB: EasyArtDB_production

volumes:
  postgres_data:
